This commit represents whayt I think will be a working solution to refactoring split_libraries to make it parallelizeable. The basic idea is to split all of the stuff responsible for processing a sequence and putting it into its own function. THe reading of files is an iterator so the indivusal work can be farmed out.
The check-seq process returns a dicitonary of all of the values necessary to do work, collate stats and write the output.
There might be a few things still missing  - actually the writing of sequences is definitely missing so I need to fix that, but the all over handling of data and passing it back to the main funciton should work.

This needs to pass tests hardcoded to use single core (no parallel benefit). If it works after that it shoudl be trivial to parellelize

pass cpus through from the split_libraries script

String formatting

change string formatting to go around string error

fix opts for ncpus

needed to correctly pass the args onward

Fix ncpus arg

must be and pass and int

change the index

fixing a mistake with index passing function. The iterator value is
unavailable until it is iterated. Therefore we need to pass the base
index value into the check_eq function and let the index be calculated
within. This means passing a tuple (idx, seq) into eh check_eq function.

some more fixes

I keep running into this error:
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup
__builtin__.function failed

I think this might be due to the filters being passed. I’ll need to
look into them

converting the quality filter classes to funtions so that they can be parallelized

put the filters into the preprocess funciton and pass them along

further refactor to put everything into a dictionary and allow that to be passed along. use the cytoolz library for its asso function and its compose funciton

get another bit working. before I was tripping an error at the median stage due to an out of phase primer argument set. I will use named arguments as much as aI possibly can to avoid this problem.

now I need to incorporate the state changes somehow: add up all the errors and the like

almost have the filters worked out

basic reporting infrastructure for split_libraries

some whitespace and name cleaning

funciton arity fixes